name: Build and Test with JaCoCo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run unit tests
        run: mvn -B test --file pom.xml

      - name: Generate JaCoCo code coverage report
        run: mvn -B jacoco:report --file pom.xml

      - name: Upload JaCoCo code coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
